language: generic
dist: bionic
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

before_install:
  - wget -c https://files.seeedstudio.com/arduino/seeed-arduino-ci.sh
script:
  - chmod +x seeed-arduino-ci.sh
  - cat $PWD/seeed-arduino-ci.sh
  - $PWD/seeed-arduino-ci.sh -b "Seeeduino:samd:seeed_wio_terminal" -s simple_demo@erpc_client/simple_demo@erpc_server Seeed-Studio/Seeed_Arduino_FreeRTOS.git
  - $PWD/seeed-arduino-ci.sh -b "Seeeduino:samd:seeed_XIAO_m0" -s simple_demo@erpc_client/simple_demo@erpc_server Seeed-Studio/Seeed_Arduino_FreeRTOS.git

notifications:
  email:
    on_success: change
    on_failure: change