/* Define the project name, which is also the prefix of all generated source code file names*/

/*
 * Generated by erpcgen 1.7.3 on Wed Jul 22 15:48:27 2020.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpc_demo_server_h_)
#define _erpc_demo_server_h_

#ifdef __cplusplus
#include "erpc_server.h"
#include "erpc_codec.h"
extern "C"
{
#include "erpc_demo.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 10703 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


/*!
 * @brief Service subclass for DEMO.
 */
class DEMO_service : public erpc::Service
{
public:
    DEMO_service() : Service(kDEMO_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for RD_demoHello1 of DEMO interface. */
    erpc_status_t RD_demoHello1_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for RD_demoHello2 of DEMO interface. */
    erpc_status_t RD_demoHello2_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for RD_demoHello3 of DEMO interface. */
    erpc_status_t RD_demoHello3_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "erpc_demo.h"
#endif // __cplusplus

typedef void * erpc_service_t;

erpc_service_t create_DEMO_service(void);

void destroy_DEMO_service(void);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _erpc_demo_server_h_
